#!/bin/zsh

file_changed() {
    if [ -f "$GIT_DIR"./$1 ]
    then
        CHANGED=""
        if [ -z "$3" ]
        then
            CHANGED=$(git diff "$2" --stat -- "$GIT_DIR"./$1 | wc -l)
        else
            CHANGED=$(git diff "$2" "$3" --stat -- "$GIT_DIR"./$1 | wc -l)
        fi
        if [ $CHANGED -gt 0 ];
        then
            echo ""
            echo -e "\e[31m$1 has changed!\e[0m"
            return 0
        fi
        return 1
    else
        return 1
    fi
}

if file_changed "Cartfile.resolved" $1 $2;
then
    carthage update
fi

if file_changed "Gemfile.lock" $1 $2;
then
    bundle install
fi

if file_changed "Podfile.lock" $1 $2;
then
    bundle exec pod install || pod install
fi

