#!/usr/bin/env python

import random
import string
import sys

if __name__ == "__main__":
    length = 20
    try:
        length = int(sys.argv[1])
    except:
        pass
    print(''.join(random.choice(string.ascii_uppercase + string.ascii_lowercase + string.digits) for _ in range(length)))
