#!/usr/bin/env zsh

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
DIFF=$(git diff --cached)

cgip <<EOF
Write a suggested commit message for the diff, I am using the branch name
$BRANCH_NAME, write it as if you wrote the changes, do not answer with anything
else than the message itself. Do not answer with quotes

$DIFF
EOF

