#!/usr/bin/env zsh

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
DIFF=$(git diff --cached)

echo $DIFF | cgip "Write a suggested commit message for the diff, I am using the branch name $BRANCH_NAME, write it as if you wrote the changes"
