#!/usr/bin/env zsh

TMPFILE=$(mktemp).out

# -J: join lines, removes soft wraps
# -p: output to stdout
# -S: start at the beginning of the history
tmux capture-pane -J -pS - > $TMPFILE

# create a new window with the output

tmux new-window -n "output" "nvim -c 'norm G' $TMPFILE"
