#!/usr/bin/env zsh

TMPFILE=$(mktemp).out

# -J: join lines, removes soft wraps
# -p: output to stdout
# -S: start at the beginning of the history
tmux capture-pane -J -pS - > $TMPFILE

PANE_TOP=$(tmux display-message -p '#{pane_top}')
PANE_LEFT=$(tmux display-message -p '#{pane_left}')
PANE_RIGHT=$(tmux display-message -p '#{pane_right}')
PANE_BOTTOM=$(($(tmux display-message -p '#{pane_bottom}') + 1))

WIDTH=$(($PANE_RIGHT - $PANE_LEFT))
HEIGHT=$(($PANE_BOTTOM - $PANE_TOP))

# -E: close popup on exit
# -B: Do not show popup border
tmux display-popup -E -B -x $PANE_LEFT -y $PANE_BOTTOM -w $WIDTH -h $HEIGHT "nvim -c 'norm G' $TMPFILE"

