#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-merge.\n"; exit 2; }
git lfs post-merge "$@"

# CHANGED=$(git diff  --stat -- "$GIT_DIR"Cartfile.resolved | wc -l)
# if [ "$CHANGED" -gt 0 ];
# then
#     echo "Cartfile.resolved has changed!"
#     sh "$GIT_DIR"./fastlane/carthage-update.sh
# fi

git submodule update --recursive

./.git/hooks/check_dependency_lockfile $(git rev-parse HEAD@{1})

git log --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --graph "$(git rev-parse HEAD@{1})..$(git rev-parse HEAD)"
