#!/bin/sh

lint_output=$(exec swiftlint --strict 2>&1)
ret_code=$?
PWDSTRING=$(pwd | sed -e 's/[\/&]/\\&/g')

if [ $ret_code != 0 ]; then
    echo "$lint_output" | grep -v "^Linting" | sed "s/$PWDSTRING//g"
    exit $ret_code
fi

./.git/hooks/stricter-swiftlint.sh
if [ $? != 0 ]; then
    exit 1
fi

if [ -f ./test_output ]; then
    echo "test_output exists"
    exit 1
fi

if [ -d ./test_output ]; then
    echo "test_output exists"
    exit 1
fi

circleci config validate

if [ $? != 0 ]; then
    exit 1
fi

#codeowners-checker check --no-interactive

#if [ $? != 0 ]; then
#    exit 1
#fi

ruby -c fastlane/Fastfile

if [ $? != 0 ]; then
    exit 1
fi
#
# Check syntax of all ruby files.
#files=$(git diff --chached | grep -E "Fastfile|.*\.rb")
#while read -r file; do
#    ruby -wc "$file" > /dev/null
#    if [ $? != 0 ]; then
#        exit 1
#    fi
#done <<< "$files"
#
#
#cd fastlane
#bundle exec rspec
#cd ..
#
#if [ $? != 0 ]; then
#    exit 1
#fi
