#!/bin/sh

if [ -f "$GIT_DIR"./.swiftlint.yml ]
then
    lint_output=$(exec swiftlint --strict 2>&1)
    ret_code=$?
    PWDSTRING=$(pwd | sed -e 's/[\/&]/\\&/g')

    if [ $ret_code != 0 ]; then
        echo "$lint_output" | grep -v "^Linting" | sed "s/$PWDSTRING//g"
        exit $ret_code
    fi

    ./.git/hooks/stricter-swiftlint.sh
    if [ $? != 0 ]; then
        exit 1
    fi

    if [ -f ./swiftlint.html ]; then
        echo "swiftlint.html exists"
        exit 1
    fi
fi

if [ -f ./test_output ]; then
    echo "test_output exists"
    exit 1
fi

if [ -d ./test_output ]; then
    echo "test_output exists"
    exit 1
fi

if [ -f "$GIT_DIR"./.circleci/config.yml ]
then
    circleci config validate
    if [ $? != 0 ]; then
        exit 1
    fi
fi


#codeowners-checker check --no-interactive

#if [ $? != 0 ]; then
#    exit 1
#fi


if [ -f "$GIT_DIR"./fastlane/Fastfile ]
then
    ruby -c fastlane/Fastfile

    if [ $? != 0 ]; then
        exit 1
    fi
fi

if [ -f "GIT_DIR"./.rubocop.yml ]
then
    rubocop
    if [ $? != 0]
    then
        exit 1
    fi
fi
