#!/usr/bin/env zsh

if [[ $# -eq 1 ]]; then
    selected=$1
else
    if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
        selected=$(find ~/workspace/quickbit ~/dotfiles ~/workspace ~ -mindepth 1 -maxdepth 1 -type d | fzf)
    else
        : ${tmp_dir:=${TMPPREFIX:-/tmp/zsh}-fzf-tab-$USER}
        sessions=$(tmux list-sessions)
        session_names=$(echo $sessions | cut -d ':' -f 1)
        directories=$(find ~/workspace/quickbit ~/dotfiles ~/workspace ~ -mindepth 1 -maxdepth 1 -type d | grep -v "$session_names$")

        selected=$({ echo $sessions; echo $directories } | fzf-tmux -p --preview 'tmux list-windows -t $(echo {} | cut -d ":" -f 1) 2> /dev/null || ls -l {}')
        if [[ ! -d $selected ]]; then
            selected=$(echo $selected | cut -d ':' -f 1)
        fi
    fi
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
