---
- name: Install MacOS Packages
  hosts: localhost
  become: false
  tasks:
    - name: Install packages
      command:
        brew install jq
      register: out
    - debug: msg="{{ out.stdout }}"
    - debug: msg="{{ out.stderr }}"
